services:
    _defaults:
        autowire: true
        autoconfigure: true # virer ?
        public: false

    Kibatic\CmsBundle\Controller\BlockController:
        tags: ['controller.service_arguments']

    Kibatic\CmsBundle\Form\TextBlockType: ~
    Kibatic\CmsBundle\Form\ImageBlockType: ~
    Kibatic\CmsBundle\Form\HtmlBlockType: ~
    Kibatic\CmsBundle\Form\AlertBlockType: ~

    _instanceof:
        Kibatic\CmsBundle\Form\BlockTypeInterface:
            tags: [ 'cms.block_type' ]

    Kibatic\CmsBundle\Repository\BlockRepository:
#        class: Kibatic\CmsBundle\Repository\BlockRepository
#        factory: ['@doctrine.orm.entity_manager', 'getRepository']
#        arguments:
#            - Kibatic\CmsBundle\Entity\Block

    Kibatic\CmsBundle\BlockTypeChain:

    Kibatic\CmsBundle\Twig\BlockExtension:
        public: true
        tags:
            - { name: twig.extension }
